### ISSUE TITLE
Runtime issue with get_r-function and get_bubbletree_graph-function grabbing all available CPUs

### ISSUE THREAD

**Issue by AnjaMJ** [snaketron/scBubbletree#1]
Hi,
I think your tool looks really cool and I'm curious to try it out on my own data.
I got everything installed and running fine on our servers (see specifications below)

But when I try to run on my own dataset, the process hangs forever at
`2) gap statistic`

My dataset is 192.436 cells using 30 PCs with the code below
`b_r <- get_r(B_gap = 5,
             rs = 10^seq(from = -1.5, to = 0, by = 0.1),
             x = A,
             n_start = 10, 
             iter_max = 50,
             algorithm = "original",
             knn_k = 50,
             cores = 8)`

I have successfully run subsets of 10.000, 20.000, 40.000, 100.000 cells at reasonable runtimes, but at 150.000 cells the process runs for 10 hours, and with the full dataset it never finishes
![Screenshot 2023-05-26 at 07 53 41](https://github.com/snaketron/scBubbletree/assets/23075868/e394c527-5760-4522-a620-d1bd2c89b29a)

I have gotten it to run on all cells using 15 PCs (finished in 1.32 hours ) so I don't understand the runtime issue when adding more PCs.

The next step in your gives me problems with cores. Even with your small test-dataset, the code grabs all the cores available on our server. I have also run the code with cores=1 (no parallelization) and it still grabs all cores.
`r_louvain <- get_bubbletree_graph(x = A,
                                   r = 0.28,
                                   n_start = 20,
                                   iter_max = 100,
                                   algorithm = "original",
                                   knn_k = 50,
                                   cores = 8,
                                   B = 200,
                                   N_eff = 200,
                                   round_digits = 1,
                                   show_simple_count = FALSE)`

Specifications:
Running R.4.2 through jupyter in a conda environment
[conda_env_list.txt](https://github.com/snaketron/scBubbletree/files/11574610/conda_env_list.txt)
[R_session.txt](https://github.com/snaketron/scBubbletree/files/11574667/R_session.txt)

**Comment by snaketron** [comment]
Hi @AnjaMJ,

sorry for the late reply, I missed your message somehow.


> But when I try to run on my own dataset, the process hangs forever at
> 2) gap statistic
> 
> My dataset is 192.436 cells using 30 PCs with the code below
> b_r <- get_r(B_gap = 5, rs = 10^seq(from = -1.5, to = 0, by = 0.1), x = A, n_start = 10,  iter_max = 50, algorithm = > "original", knn_k = 50, cores = 8)
> 
> I have successfully run subsets of 10.000, 20.000, 40.000, 100.000 cells at reasonable runtimes, but at 150.000 cells the process runs for 10 hours, and with the full dataset it never finishes


Running get_r can be computationally intensive for extremely large datasets, such as yours.

You are basically running `B_gap`=5  x `rs= 10^seq(from = -1.5, to = 0, by = 0.1)` = 16 -> 80 clustering runs on a very large data.

More PCs -> more features -> the clustering simply takes longer (e.g. see how the complexity increases with number of features in k-means clustering: https://en.wikipedia.org/wiki/K-means_clustering)

For the first run I recommend starting with e.g. B_gap = 1 and rs=10^seq(from = -2, to = 0, by = 0.5). Given the size of the data (number of cells) you will obtain reasonable and stable results even with B_gap = 1.



> The next step in your gives me problems with cores. Even with your small test-dataset, the code grabs all the cores available on our server. I have also run the code with cores=1 (no parallelization) and it still grabs all cores.

Thank you for pointing this out, I will have a look at the code. I suspect that some of the stringdist package operations will try to grab as many cores as available. Will let you know soon. (update: negative this is not the problem)

> r_louvain <- get_bubbletree_graph(x = A, r = 0.28, n_start = 20, iter_max = 100, algorithm = "original", knn_k = 50, cores = 8, B = 200, N_eff = 200, round_digits = 1, show_simple_count = FALSE)

@AnjaMJ Executing this line of code should grab 8 cores.

> r_louvain <- get_bubbletree_graph(x = A, r = 0.28, n_start = 20, iter_max = 100, algorithm = "original", knn_k = 50, cores = 1, B = 200, N_eff = 200, round_digits = 1, show_simple_count = FALSE)

@AnjaMJ and as you pointed out, this should take 1 core. This is the behavior I observe under version 1.1.9, i.e. unfortunately I cannot reproduce this problem with the small data set from the vignette and cores set to 1.

**Comment by AnjaMJ** [comment]
Hi @snaketron !
Thanks for your reply.
With `B_gap = 1 and rs=10^seq(from = -2, to = 0, by = 0.5)` I can run the function on my full dataset in a reasonable time. Too bad about the `get_bubbletree_graph` -  function. My run is still grabbing all cores

**Comment by snaketron** [comment]
@AnjaMJ 

> Thanks for your reply.
With B_gap = 1 and rs=10^seq(from = -2, to = 0, by = 0.5) I can run the function on my full dataset in a reasonable time. 

Perfect!

> Too bad about the get_bubbletree_graph - function. My run is still grabbing all cores

Unfortunately there is not much I can do to help on this end, as I have not been able to reproduce this behavior of the function, and I tried different linux servers (see screenshot)

![top](https://github.com/snaketron/scBubbletree/assets/5060977/f44e7cfb-bd0d-4d27-9de3-20bcff742384)


Can you try running the example script  (and check the CPU usage) on another PC to isolate whether this is an issue with your server or a more general one:

```
# input data
data("d_500", package = "scBubbletree")
A <- d_500$A

b <- get_bubbletree_graph(x = A,
                          r = 1,
                          B = 500,
                          N_eff = 100,
                          n_start = 20,
                          iter_max = 100,
                          algorithm = "original",
                          knn_k = 50,
                          hclust_method = "average",
                          hclust_distance = "euclidean",
                          cores = 1,
                          round_digits = 2,
                          show_simple_count = FALSE)
```

If the function still grabs all cores then the only way I may be able to help is if you provided a screenshot of your CPU usage + the script you are using


Now I noticed that you are using scBubbletree version 1.0. Maybe you should try getting the newest one 1.2 from Bioconductor.


Best
