### ISSUE TITLE
Rendering the vignette

### ISSUE THREAD

**Issue by federicomarini** [snaketron/scBubbletree#3]
Hi there!

Thanks for your package 👍 

While checking the vignette on Bioc I noticed it is rendered so

<img width="721" alt="image" src="https://github.com/user-attachments/assets/e2f7a90a-be8d-4b3b-a9ac-a631667fe6ad">

This can be for the knitr option being misspecified here:

https://github.com/federicomarini/scBubbletree/blob/604324024c8617ad10ec1dceadd85efa3df294d8/vignettes/User_manual.Rmd#L14

This can be easily fixed by specifying a character string, a simple PR is coming in from my fork if you want to review that directly

Federico

**Comment by federicomarini** [comment]
In the PR it is fully specified as string, `#>` to have it stand out as being output.

Alternative: one can also use the empty `""` string if you want simply nothing there.

I tend to like the `#>` to make clear it is not a command to enter 😉 

<img width="397" alt="image" src="https://github.com/user-attachments/assets/eeff94ae-2f1c-42b7-88a3-9f858a8728dd">

**Comment by snaketron** [comment]
Super helpful, thanks for the suggestion!

**Comment by federicomarini** [comment]
You're very welcome!
Congratulations on the freshly brewed manuscript on it ❤️
